{{- if .Values.agentSchedule.enabled }}
apiVersion: nvt.dev/v1alpha1
kind: AgentSchedule
metadata:
  name: {{ .Values.agentSchedule.name | quote }}
  namespace: {{ include "nvt.namespace" . | quote }}
  labels:
    {{- include "nvt.labels" . | nindent 4 }}
spec:
  maxParallelism: {{ .Values.agentSchedule.maxParallelism }}
  suspend: {{ .Values.agentSchedule.suspend }}
  {{- with .Values.agentSchedule.template }}
  {{- $template := deepCopy . }}
  {{- if not (get $template "image") }}
  {{- $_ := set $template "image" (include "nvt.runtimeImage" $) }}
  {{- end }}
  template:
    {{- toYaml $template | nindent 4 }}
  {{- end }}
  {{- with .Values.agentSchedule.profiles }}
  profiles:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agentSchedule.profileSelection }}
  profileSelection:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agentSchedule.allowedProducers }}
  allowedProducers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
