{{- if .Values.broker.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvt-broker-config
  labels:
    {{- include "nvt.brokerLabels" . | nindent 4 }}
data:
  broker.yaml: |
{{ toYaml .Values.broker.config | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvt-broker-agents
  labels:
    {{- include "nvt.brokerLabels" . | nindent 4 }}
data:
  agents.yaml: |
{{ toYaml .Values.broker.agents | indent 4 }}
{{- end }}
