{{- if and .Values.producer.enabled .Values.producer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nvt.producerServiceAccountName" . }}
  namespace: {{ include "nvt.namespace" . | quote }}
  labels:
    {{- include "nvt.producerLabels" . | nindent 4 }}
{{- end }}
