{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nvt-github-comments-producer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nvt-github-comments-producer.labels" . | nindent 4 }}
{{- end }}
